const materi = [
  {id:1,kategori:"Al-Qur'an",judul:"Belajar Tajwid Dasar",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/tajwid.svg",deskripsi:"Pembelajaran dasar ilmu tajwid untuk membantu membaca Al-Qur'an dengan baik dan benar.",video:{tersedia:true,url:"https://www.youtube.com/embed/dQw4w9WgXcQ",durasi:"18:45"},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:true,url:"pdf/tajwid-dasar.pdf",nama:"Modul Belajar Tajwid Dasar.pdf",ukuran:"Demo"}},
  {id:2,kategori:"Tafsir",judul:"Tafsir Surat Al-Fatihah",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/alfatihah.svg",deskripsi:"Mempelajari makna dan kandungan Surat Al-Fatihah secara ringkas dan mudah dipahami.",video:{tersedia:true,url:"https://www.youtube.com/embed/dQw4w9WgXcQ",durasi:"25:30"},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:true,url:"pdf/tafsir-al-fatihah.pdf",nama:"Modul Tafsir Surat Al-Fatihah.pdf",ukuran:"Demo"}},
  {id:3,kategori:"Fiqih",judul:"Panduan Wudhu yang Benar",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/wudhu.svg",deskripsi:"Panduan tata cara wudhu yang benar berdasarkan tuntunan syariat.",video:{tersedia:false,url:"",durasi:""},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:true,url:"pdf/panduan-wudhu.pdf",nama:"Panduan Wudhu.pdf",ukuran:"Demo"}},
  {id:4,kategori:"Aqidah",judul:"Mengenal Rukun Iman",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/aqidah.svg",deskripsi:"Pembelajaran dasar tentang enam rukun iman dan penerapannya dalam kehidupan.",video:{tersedia:true,url:"https://www.youtube.com/embed/dQw4w9WgXcQ",durasi:"15:20"},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:false,url:"",nama:"",ukuran:""}},
  {id:5,kategori:"Akhlak",judul:"Adab Menuntut Ilmu",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/adab.svg",deskripsi:"Pembelajaran mengenai adab dan sikap seorang muslim dalam menuntut ilmu.",video:{tersedia:true,url:"https://www.youtube.com/embed/dQw4w9WgXcQ",durasi:"22:10"},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:true,url:"pdf/adab-menuntut-ilmu.pdf",nama:"Modul Adab Menuntut Ilmu.pdf",ukuran:"Demo"}},
  {id:6,kategori:"Hadits",judul:"Hadits Tentang Niat",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/hadits.svg",deskripsi:"Mempelajari hadits tentang pentingnya niat dalam setiap amal.",video:{tersedia:true,url:"https://www.youtube.com/embed/dQw4w9WgXcQ",durasi:"17:40"},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:false,url:"",nama:"",ukuran:""}},
  {id:7,kategori:"Bahasa Arab",judul:"Kosakata Bahasa Arab Dasar",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/arab.svg",deskripsi:"Mengenal kosakata Bahasa Arab dasar yang sering digunakan dalam kehidupan sehari-hari.",video:{tersedia:true,url:"https://www.youtube.com/embed/dQw4w9WgXcQ",durasi:"30:10"},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:false,url:"",nama:"",ukuran:""}},
  {id:8,kategori:"Sirah",judul:"Kisah Kelahiran Nabi Muhammad ﷺ",pengajar:"Ust. Ahmad",level:"Pemula",thumbnail:"assets/img/sirah.svg",deskripsi:"Mengenal sejarah kelahiran Rasulullah ﷺ dan keadaan masyarakat Arab sebelum Islam.",video:{tersedia:true,url:"https://www.youtube.com/embed/dQw4w9WgXcQ",durasi:"28:30"},audio:{tersedia:false,url:"",durasi:""},pdf:{tersedia:false,url:"",nama:"",ukuran:""}}
];